name: go test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.4
      - name: Install dependencies
        run: go get .
      - name: Run Tests
        run: go test -v ./... > results.json
      - name: Store results
        uses: actions/upload-artifact@master
        with:
          name: TestResults
          path: results.json
      - name: Run Snyk
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload results to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
